/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 62dd70807c373c63d143a6ab92d66f81)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		AGENTCRIBS_KV: KVNamespace;
		AGENTCRIBS_R2: R2Bucket;
		SEND_EMAIL: SendEmail;
		ASSETS: Fetcher;
		ADMIN_PASSWORD: string;
		ADMIN_COOKIE_NAME: string;
		GITHUB_CLIENT_ID: string;
		GITHUB_CLIENT_SECRET: string;
		GITHUB_CALLBACK_URL: string;
		SEND_EMAIL_FROM: string;
		APP_URL: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_PASSWORD" | "ADMIN_COOKIE_NAME" | "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET" | "GITHUB_CALLBACK_URL" | "SEND_EMAIL_FROM" | "APP_URL">> {}
}
