/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: ca41a1f42392ca528cbc5831ca503926)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		AGENTCRIBS_KV: KVNamespace;
		AGENTCRIBS_R2: R2Bucket;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
