/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 13360c4b63db8a948979c0f301cf05ef)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		AGENTCRIBS_KV: KVNamespace;
		AGENTCRIBS_R2: R2Bucket;
		ASSETS: Fetcher;
		ADMIN_PASSWORD: string;
		ADMIN_COOKIE_NAME: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_PASSWORD" | "ADMIN_COOKIE_NAME">> {}
}
